# docker-compose -f docker-compose.develop.yml up --build
version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.develop
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017
    depends_on:
      - database
  
  database:
    image: mongo:4.1.6
    container_name: "database"
    ports:
      - 27017:27017